blank_issues_enabled: false
contact_links:
  - name: @fsegurai/ngx-codemirror Issues
    url: https://github.com/fsegurai/ngx-codemirror/issues
    about: This is for development, support and technical issues/questions.
